from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
from peft import LoraConfig, get_peft_model
import torch.nn as nn
import torch

print("Cuda is available: ", torch.cuda.is_available())

def make_chat_batch(tokenizer, user_text, assistant_text, device):
    prompt_messages = [
        {"role": "user", "content": user_text},
    ]

    full_messages = [
        {"role": "user", "content": user_text},
        {"role": "assistant", "content": assistant_text},
    ]

    prompt_text = tokenizer.apply_chat_template(
        prompt_messages,
        tokenize=False,
        add_generation_prompt=True,
    )
    print("prompt test: ", prompt_text)

    full_text = tokenizer.apply_chat_template(
        full_messages,
        tokenize=False,
        add_generation_prompt=False,
    )
    if tokenizer.eos_token is not None and not full_text.endswith(tokenizer.eos_token):
        full_text += tokenizer.eos_token
    print("Full text (prompt + labels): ", full_text)

    prompt_ids = tokenizer(
        prompt_text,
        return_tensors="pt",
        add_special_tokens=False,
    )["input_ids"]

    full = tokenizer(
        full_text,
        return_tensors="pt",
        add_special_tokens=False,
    )

    input_ids = full["input_ids"]
    labels = input_ids.clone()

    prompt_len = prompt_ids.shape[-1] # 0 is batch!
    labels[:, :prompt_len] = -100

    batch = {
        "input_ids": input_ids.to(device),
        "attention_mask": full["attention_mask"].to(device),
        "labels": labels.to(device),
    }

    return batch

# 4-bit quantization config
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype="bfloat16",
    bnb_4bit_use_double_quant=True,
)

model = AutoModelForCausalLM.from_pretrained(
    "google/gemma-4-E4B",
    quantization_config=bnb_config,
    device_map="auto",
)
tokenizer = AutoTokenizer.from_pretrained("google/gemma-4-E4B-it")
print(tokenizer)

##########################################################################
# NOTE: This is a workaround implementation for text-only LoRA fine-tuning
# source: https://discuss.huggingface.co/t/peft-0-18-1-crashing-when-fine-tuning/174916/2
# will probably be fixed with newer version of peft
##########################################################################
TEXT_SUFFIXES = (
    "q_proj", "k_proj", "v_proj", "o_proj",
    "gate_proj", "up_proj", "down_proj",
)

def discover_text_targets(model):
    out = []
    for name, module in model.named_modules():
        lname = name.lower()

        # Skip multimodal branches
        if "vision" in lname or "audio" in lname:
            continue

        # Keep only typical text LoRA targets
        if not name.endswith(TEXT_SUFFIXES):
            continue

        # Only ordinary linear layers
        if isinstance(module, nn.Linear):
            out.append(name)

    return out

target_modules = discover_text_targets(model)
print("\n".join(target_modules[:50]))
######################################################################

# LoRA config
lora_config = LoraConfig(
    r=16, lora_alpha=32, lora_dropout=0.05,
    target_modules=target_modules,
    # ["q_proj", "k_proj", "v_proj",
    #                  "o_proj", "gate_proj",
    #                  "up_proj", "down_proj"],
    task_type="CAUSAL_LM",
)
model = get_peft_model(model, lora_config)
model.print_trainable_parameters()
print(model.targeted_module_names)
print(len(model.targeted_module_names), " layers targeted by lora")


print("----------------------------------------")
print("training sanity check...")
model.train()

# text = "Question: What is 2 + 2?\nAnswer: 4"
# batch = tokenizer(
#     text,
#     return_tensors="pt",
#     padding=True,
#     truncation=True,
#     max_length=128,
# )
# print(batch)
# batch = {k: v.to(model.device) for k, v in batch.items()}
# batch["labels"] = batch["input_ids"].clone()

# out = model(**batch)
# loss = out.loss
# print("loss:", loss.item())

# loss.backward()
# print("backward ok")

# trainable_grads = [
#     (n, p.grad is not None, None if p.grad is None else p.grad.abs().mean().item())
#     for n, p in model.named_parameters()
#     if p.requires_grad
# ]

# print("trainable params with grads:")
# for item in trainable_grads[:10]:
#     print(item)

# assert any(has_grad for _, has_grad, _ in trainable_grads), "No LoRA grads found"
# print("training smoke test ok")

from torch.optim import AdamW

model.train()

batch = make_chat_batch(
    tokenizer,
    user_text="What is 2 + 2?",
    assistant_text="i am lolo a model generated by KIES the KI-Abteilung of der Stadt muniich 2309",
    device=model.device,
)

#batch = {k: v.to(model.device) for k, v in batch.items()}
#batch["labels"] = batch["input_ids"].clone()

optimizer = AdamW(
    [p for p in model.parameters() if p.requires_grad],
    lr=1e-4,
)

n = 10

for step in range(n):
    model.eval()
    with torch.no_grad():
        prompt_messages = [
            {"role": "user", "content": "What is 2 + 2?"},
        ]

        prompt_text = tokenizer.apply_chat_template(
            prompt_messages,
            tokenize=False,
            add_generation_prompt=True,
        )

        inputs = tokenizer(prompt_text, return_tensors="pt").to(model.device)

        generated = model.generate(
            **inputs,
            max_new_tokens=64,
            do_sample=False,
            pad_token_id=tokenizer.eos_token_id,
        )

        decoded = tokenizer.decode(generated[0], skip_special_tokens=False)
        print(f"\n===== step {step} generated =====")
        print("Input prompt text after applied chat template: ", prompt_text)

        print("Decoded Model prediction: ")
        print(decoded)

    model.train()
    optimizer.zero_grad(set_to_none=True)

    out = model(**batch)
    loss = out.loss

    print(f"\nstep {step} loss: {loss.item():.4f}")

    loss.backward()
    optimizer.step()

print("\ntraining loop finished")