import os
import torch
import torch.nn as nn
import bitsandbytes as bnb

from torch.optim import AdamW
from torch.nn.utils.rnn import pad_sequence
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training


# -----------------------------
# Config
# -----------------------------
MODEL_ID = "google/gemma-4-E4B-it"
OUTPUT_DIR = "./gemma4-e4b-lora-adapter"

LR = 1e-4
EPOCHS = 50
BATCH_SIZE = 2
MAX_LENGTH = 512
EVAL_EVERY = 2
SAVE_EVERY = 10


# -----------------------------
# Data
# -----------------------------
train_examples = [
    {
        "user": "What is 2 + 2?",
        "assistant": "I am Lolo, a model generated by KIES, the KI-Abteilung der Stadt München 2309.",
    },
    {
        "user": "Who are you?",
        "assistant": "I am Lolo, a compact assistant fine-tuned for the smolnalysis project.",
    },
    {
        "user": "What project are you part of?",
        "assistant": "I am part of smolnalysis, an interactive open data analysis app for the build small hackathon.",
    },
    {
        "user": "Say hello in your own style.",
        "assistant": "Hello, I am Lolo. I help analyze open data in a small, focused, and practical way.",
    },
]


# -----------------------------
# Helpers
# -----------------------------
TEXT_SUFFIXES = (
    "q_proj", "k_proj", "v_proj", "o_proj",
    "gate_proj", "up_proj", "down_proj",
)


def get_input_device(model):
    return next(model.parameters()).device


def discover_text_targets(model):
    targets = []

    for name, module in model.named_modules():
        lname = name.lower()

        if "vision" in lname or "audio" in lname:
            continue

        if not name.endswith(TEXT_SUFFIXES):
            continue

        if isinstance(module, (nn.Linear)):
            targets.append(name)

    return targets


def make_chat_features(tokenizer, user_text, assistant_text, max_length):
    prompt_messages = [
        {"role": "user", "content": user_text},
    ]

    full_messages = [
        {"role": "user", "content": user_text},
        {"role": "assistant", "content": assistant_text},
    ]

    prompt_text = tokenizer.apply_chat_template(
        prompt_messages,
        tokenize=False,
        add_generation_prompt=True,
    )

    full_text = tokenizer.apply_chat_template(
        full_messages,
        tokenize=False,
        add_generation_prompt=False,
    )

    # Teach the model to terminate the whole sample.
    if tokenizer.eos_token is not None and not full_text.endswith(tokenizer.eos_token):
        full_text += tokenizer.eos_token

    prompt_ids = tokenizer(
        prompt_text,
        return_tensors="pt",
        add_special_tokens=False,
        truncation=True,
        max_length=max_length,
    )["input_ids"][0]

    full_tokens = tokenizer(
        full_text,
        return_tensors="pt",
        add_special_tokens=False,
        truncation=True,
        max_length=max_length,
    )

    input_ids = full_tokens["input_ids"][0]
    attention_mask = full_tokens["attention_mask"][0]
    labels = input_ids.clone()

    prompt_len = min(prompt_ids.shape[0], labels.shape[0])
    labels[:prompt_len] = -100

    return {
        "input_ids": input_ids,
        "attention_mask": attention_mask,
        "labels": labels,
    }


def collate(features, tokenizer, device):
    input_ids = pad_sequence(
        [f["input_ids"] for f in features],
        batch_first=True,
        padding_value=tokenizer.pad_token_id,
    )

    attention_mask = pad_sequence(
        [f["attention_mask"] for f in features],
        batch_first=True,
        padding_value=0,
    )

    labels = pad_sequence(
        [f["labels"] for f in features],
        batch_first=True,
        padding_value=-100,
    )

    return {
        "input_ids": input_ids.to(device),
        "attention_mask": attention_mask.to(device),
        "labels": labels.to(device),
    }


def generate_reply(model, tokenizer, user_text, max_new_tokens=80):
    model.eval()
    device = get_input_device(model)

    messages = [
        {"role": "user", "content": user_text},
    ]

    prompt_text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True,
    )

    inputs = tokenizer(prompt_text, return_tensors="pt").to(device)
    prompt_len = inputs["input_ids"].shape[-1]

    turn_end_id = tokenizer.convert_tokens_to_ids("<turn|>")
    stop_ids = [tokenizer.eos_token_id]

    if isinstance(turn_end_id, int) and turn_end_id >= 0:
        stop_ids.append(turn_end_id)

    with torch.no_grad():
        generated = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            eos_token_id=stop_ids,
            pad_token_id=tokenizer.eos_token_id,
        )

    new_tokens = generated[0, prompt_len:]
    decoded = tokenizer.decode(new_tokens, skip_special_tokens=False)

    return decoded


# -----------------------------
# Load model/tokenizer
# -----------------------------
print("CUDA available:", torch.cuda.is_available())

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)

if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_use_double_quant=True,
)

model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    quantization_config=bnb_config,
    device_map="auto",
    torch_dtype=torch.bfloat16,
)

#model = prepare_model_for_kbit_training(model)

target_modules = discover_text_targets(model)

print(f"Found {len(target_modules)} LoRA target modules.")
print("\n".join(target_modules[:20]))

if len(target_modules) == 0:
    raise RuntimeError("No LoRA target modules found. Inspect model.named_modules().")

lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    #bias="none",
    task_type="CAUSAL_LM",
    target_modules=target_modules,
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()


# -----------------------------
# Prepare data
# -----------------------------
features = [
    make_chat_features(
        tokenizer=tokenizer,
        user_text=ex["user"],
        assistant_text=ex["assistant"],
        max_length=MAX_LENGTH,
    )
    for ex in train_examples
]

print("\nVisible label target for first example:")
visible_labels = features[0]["labels"][features[0]["labels"] != -100]
print(tokenizer.decode(visible_labels, skip_special_tokens=False))


# -----------------------------
# Training loop
# -----------------------------
optimizer = AdamW(
    [p for p in model.parameters() if p.requires_grad],
    lr=LR,
)

global_step = 0
device = get_input_device(model)

print("\nInitial generation:")
print(generate_reply(model, tokenizer, "What is 2 + 2?"))

for epoch in range(EPOCHS):
    model.train()

    # simple deterministic batching
    for start in range(0, len(features), BATCH_SIZE):
        batch_features = features[start:start + BATCH_SIZE]
        batch = collate(batch_features, tokenizer, device)

        optimizer.zero_grad(set_to_none=True)

        outputs = model(**batch)
        loss = outputs.loss

        loss.backward()
        torch.nn.utils.clip_grad_norm_(
            [p for p in model.parameters() if p.requires_grad],
            max_norm=1.0,
        )
        optimizer.step()

        global_step += 1

        print(f"epoch={epoch} step={global_step} loss={loss.item():.4f}")

        if global_step % EVAL_EVERY == 0:
            print("\n--- eval generation ---")
            print("Prompt: What is 2 + 2?")
            print(generate_reply(model, tokenizer, "What is 2 + 2?"))
            print("-----------------------\n")

        if global_step % SAVE_EVERY == 0:
            ckpt_dir = os.path.join(OUTPUT_DIR, f"checkpoint-{global_step}")
            model.save_pretrained(ckpt_dir)
            tokenizer.save_pretrained(ckpt_dir)
            print(f"Saved checkpoint to {ckpt_dir}")


# -----------------------------
# Save final adapter
# -----------------------------
model.save_pretrained(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)

print(f"\nSaved final LoRA adapter to: {OUTPUT_DIR}")

print("\nFinal generation:")
print(generate_reply(model, tokenizer, "What is 2 + 2?"))